### ISSUE TITLE
Support for Base64 Image

### ISSUE THREAD

**Issue by tayambamwanza** [scompiler/red-zoom-angular#16]
Currently this project will look for a file name for the input, if there was an option such as "useBase64" it could just read the data directly and allow for use of base64 string.

**Comment by 4Bos** [comment]
Hi,

What's stopping you from using images in Base64 format now?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
https://www.base64-image.de/

**Comment by tayambamwanza** [comment]
@4Bos thank you for getting back to me, I will prepare a more comprehensive description of what I'm facing, but I tried putting base64 image data into the src input directly and it didn't work. I'll get back to you  at a later stage to describe exactly what the issue is.
