### ISSUE TITLE
support to Angular 14 

### ISSUE THREAD

**Issue by busvar** [scompiler/red-zoom-angular#30]
Trying to install with angular 14 i get the error below:
 
 ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.1.0" from ngx-red-zoom@0.9.0

Is it planned any upgrade?

**Comment by blalasaadri** [comment]
We are having the same issue. For the time being, our workaround is having this line in the `.npmrc`:
```
legacy-peer-deps=true
```
(as documented [here](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps)), but that should only be a temporary workaround.

**Comment by 4Bos** [comment]
@busvar use version ``0.10.0`` which supports Angular 14.
