### ISSUE TITLE
"Freezing" feature on desktop

### ISSUE THREAD

**Issue by 4javier** [scompiler/red-zoom-angular#4]
Is it possible to get a "freezing" feature on desktop?
I mean the possibility to stick with the lens in a fixed position, being free to move the cursor around the page, scroll, etc.
At the moment on mobile it already suites my needs because, lacking gesture management, lens gets stuck on the position you tap on. Accidentally perfect. :-D
For desktop, it would be nice if you can click on a position, and get the lens fixed on that detail.

**Comment by 4Bos** [comment]
Hi,

Check version 0.5.0. It looks like it has what you need:
```html
<img
    src="image.jpg"
    redZoom="image-full.jpg"
    redZoomBehavior="click"
>
```

**Comment by 4javier** [comment]
Awesome!
I was thinking much more of a "freeze" hybrid between "click" and "hover", but even your solution fits my needs, and it's coherent with the actual behaviour on touchscreen.
- It would be helpful if you'd ship the scss used into the demo page for lens position&size, to let people simply set i.e.
```redZoomClass="red-zoom--style--window red-zoom--mode--landscape"```
- You forgot to update API description with the new available "click" value for redZoomBehavior.

Thanks a lot and keep going on with your fantastic work.
Cheers.

**Comment by 4Bos** [comment]
> I was thinking more about a "freeze" hybrid between "click" and "hover", but your solution fits my needs too, and it's coherent with the actual behaviour on touchscreen.

Yes, I was oriented on touch behavior because you said that it already suites you needs.

> It would be helpful if you'd ship the scss used into the demo page for lens position&size, to let people simply set i.e.
> `redZoomClass="red-zoom--style--window red-zoom--mode--landscape"`

Maybe, but it will probably look like this:

```
redZoomClass="red-zoom--style--window-landscape"
redZoomClass="red-zoom--style--window-square"
```

> You forgot to update API description with the new available "click" value for redZoomBehavior.

You're right. Thanks.
