### ISSUE TITLE
Styles not installed

### ISSUE THREAD

**Issue by 4javier** [scompiler/red-zoom-angular#7]
Version 0.4.0 not installing styles

> ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--14-3!./node_modules/sass-loader/dist/cjs.js??ref--14-4!./src/styles.scss)
> Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: Can't find stylesheet to import.
>    ╷
> 12 │ @import '~ngx-red-zoom/styles/base.scss';

Here you can see the whole `styles` dir is totally missing
> ls -1F  node_modules/ngx-red-zoom/
> bundles/
> esm2015/
> fesm2015/
> lib/
> ngx-red-zoom.d.ts
> ngx-red-zoom.metadata.json
> package.json
> public-api.d.ts
> README.md

Version 0.3.0 works as expected.

**Comment by 4Bos** [comment]
Hello,

Thanks, for your bug report.
Fixed in the version 0.4.1.

**Comment by van9petryk** [comment]
~ support is remove from angular v13. I have same problem while importing ngx-red-zoom@0.9.0
